server:
  port: 80
  servlet:
    context-path: /MyShop
spring:
  datasource:
    hikari:
      password: '0009'
      username: root
    url: jdbc:mysql://localhost:3306/myshopdb
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 87133212216-6fi0dd4psnr2gn9452sd9jr5pbma0bht.apps.googleusercontent.com
            client-secret: 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
            scope:
            - email
            - profile
          